 const String termsAndConditions = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '
     'Sed euismod, diam quis aliquam faucibus, '
     'nunc ipsum gravida nunc, quis aliquam diam '
     'nunc eget nisl. Sed euismod, diam quis aliquam faucibus, '
     'nunc ipsum gravida nunc, quis aliquam diam '
     'nunc eget nisl. Sed euismod, diam quis aliquam faucibus, '
     'nunc ipsum gravida nunc, quis aliquam diam '
     'nunc eget nisl. Sed euismod, diam quis aliquam faucibus, '
     'nunc ipsum gravida nunc, quis aliquam diam '
     'nunc eget nisl. Sed euismod, diam quis aliquam faucibus, '
     'nunc ipsum gravida nunc, quis aliquam diam '
     'nunc eget nisl. Sed euismod, diam quis aliquam faucibus, '
     'nunc ipsum gravida nunc, quis aliquam diam '
     'nunc eget nisl. Sed euismod, diam quis aliquam faucibus, '
     'nunc ipsum gravida nunc, quis aliquam diam '
     'nunc eget nisl. Sed euismod, diam quis aliquam faucibus, '
     'nunc ipsum gravida nunc, quis aliquam diam '
     'nunc eget nisl. Sed euismod, diam quis aliquam faucibus, '
     'nunc ipsum gravida nunc, quis aliquam diam nunc eget nisl. '
     'Sed euismod, diam quis aliquam faucibus, '
     'nunc ipsum gravida nunc, quis aliquam diam nunc eget nisl. '
     'Sed euismod, diam quis aliquam faucibus, '
     'nunc ipsum gravida nunc, quis aliquam diam nunc eget nisl. '
     'Sed euismod, diam quis aliquam faucibus, '
     'nunc ipsum gravida nunc, quis aliquam diam nunc eget nisl. '
     'Sed euismod, diam quis aliquam faucibus, '
     'nunc ipsum gravida nunc, quis aliquam diam nunc eget nisl. '
     'Sed euismod, diam quis aliquam faucibus,';